[package]
name = "unifi_avs_interface"
version = "0.0.0"
publish = false
edition.workspace = true
license.workspace = true

[dependencies]
alloy.workspace = true
eyre.workspace = true
tokio.workspace = true
alloy-node-bindings.workspace = true
thiserror.workspace = true